/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'status' : string,
  'date' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'email' : string,
  'phone' : string,
  'guests' : bigint,
  'timeSlot' : string,
}
export interface DashboardStats {
  'pendingBookings' : bigint,
  'totalBookings' : bigint,
  'confirmedBookings' : bigint,
}
export interface GalleryImage {
  'title' : string,
  'blobId' : string,
  'category' : string,
}
export interface MenuItem {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'blobId' : string,
  'category' : string,
  'price' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<[string, string, string], GalleryImage>,
  'addMenuItem' : ActorMethod<
    [string, string, string, string, string, boolean],
    MenuItem
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, bigint, string, string],
    Booking
  >,
  'deleteGalleryImage' : ActorMethod<[string], undefined>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAvailableSlots' : ActorMethod<[string], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'listMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[string, string], Booking>,
  'updateGalleryImage' : ActorMethod<
    [string, string, string, string],
    GalleryImage
  >,
  'updateMenuItem' : ActorMethod<
    [string, string, string, string, string, string, boolean],
    MenuItem
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];